pipeline {

    agent {
        dockerfile {
        filename 'docker/Dockerfile'
        }
    }
    stages {
        stage("build") {
            steps {
                sh '''/opt/build.sh
                '''
            }
        }
    }
}